### ISSUE TITLE
[Metrics] Negative Average Wait Time

### ISSUE THREAD

**Issue by amandaLi7** [cmu15122/q-prime#205]
![Screenshot 2023-01-08 at 12 15 55 AM](https://user-images.githubusercontent.com/40663739/211183201-b307d856-acbc-4e57-8c1d-6f0ff163572a.png)
Not sure how Average wait time is calculated, but it seems to be negative here. Perhaps a max(0, calculated) to add in or something, or figure out this overflow(?) issue.

**Comment by pranavaddepalli** [comment]
feature not bug
