### ISSUE TITLE
[Bug] Message history not showing up

### ISSUE THREAD

**Issue by amandaLi7** [cmu15122/q-prime#210]
One TA can't see previous messages from other TA's, only if it's from your own

**Comment by amandaLi7** [comment]
Related (?): student message is empty when messaged
<img width="820" alt="Screenshot 2023-01-18 at 6 13 55 PM" src="https://user-images.githubusercontent.com/40663739/213315819-19290439-2ba8-4c17-815c-b93c6153c5b1.png">

**Comment by angelaz1** [comment]
Unsure about the first one; the second one seems to be due to lack of validation on student fix question; adding in
