### ISSUE TITLE
Modals don't show up when using Safari on iOS

### ISSUE THREAD

**Issue by pranavaddepalli** [cmu15122/q-prime#224]
"TA is helping" doesn't pop up on Safari when on the queue on iOS until the page is refreshed. Seems to be an iOS sockets issue

**Comment by pranavaddepalli** [comment]
also on android bug with showing modals

**Comment by jacksontromero** [comment]
@pranavaddepalli Fixed this issue by adding some stuff to the NGINX config on the q server.  Added the following config options under the api routes that fix the websocket polling issue that was stopping the modals from showing on mobile.  I only tested on Android, waiting on someone with iOS to try.

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
