### ISSUE TITLE
[Bug] [priority] cannot create TAs across semesters

### ISSUE THREAD

**Issue by pranavaddepalli** [cmu15122/q-prime#238]
Cannot create new TAs from the admin page if they have been a TA in a previous semester.

Error message is a toast error saying “Validation error.”

i believe the bug is in how we interact with the semester_user table

**Comment by pranavaddepalli** [comment]
semester_user tables requires user_id to be unique

**Comment by jacksontromero** [comment]
As best we can tell, something at some point resolved this issue?  We've been unable to recreate it under any circumstances, however we'll leave this issue open for the time being in case it comes back.  If we make it through a few semester changes with no issues, then it can be closed.

**Comment by jacksontromero** [comment]
AAANDDD we figured it out - it was a deployment error on our part in which the DB for our production OHQ had an extra constraint leftover from old dev work that it shouldn't have.  Removing that fixed the issue!
